services:
  bot:
    container_name: bot_discord
    build: .
    environment:
      - NODE_ENV=production
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDIRECT_URI=${REDIRECT_URI}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
      - FRONT_URL=${FRONT_URL}
    labels:
      - "coolify.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.bot.rule=Host(`api.neko.oustopie.xyz`)"
      - "traefik.http.routers.bot.entrypoints=https"
      - "traefik.http.routers.bot.tls=true"
      - "traefik.http.services.bot.loadbalancer.server.port=3000"
    expose:
      - "3000"
    restart: on-failure
    command: ["curl", "-X", "PUT", "http://localhost:3000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - coolify

networks:
  coolify:
    external: true
