import type { TextChannel } from "discord.js";
import type { MessageCommandContext } from "types/message-command";
import { MessageCommand } from "types/message-command";

export default class LLMGuild extends MessageCommand {
  public readonly data = {
    name: "LLM Guild",
    description: "Ping the bot and reply with a message generated by AI",
  };

  shouldExecute({ client, message }: MessageCommandContext): boolean {
    return Boolean(
      client.user &&
        !message.author.bot &&
        message.mentions.has(client.user) &&
        message.inGuild(),
    );
  }

  async execute({ client, message }: MessageCommandContext): Promise<void> {
    const channel = message.channel as TextChannel;
    const llm = client.llm;

    await channel.sendTyping();
    const response = await llm.generateMessage(message.content);
    await channel.send(response);
  }
}
